### PR TITLE
Remove msgpack encoding/decoding options

### LINKED ISSUE #20: msgpack-python is deprecated, use msgpack
> This package is deprecated. Install msgpack instead.

https://pypi.org/project/msgpack-python/

When users install both msgpack and aiorpc they will have both msgpack and msgpack-python installed, which conflict.

### PR DESCRIPTION
**Pull request by nedsociety**
Fixes #20 and https://travis-ci.org/github/choleraehyq/aiorpc/builds/690660540 .

This change DOES affect aiorpc interface as well so might need minor version bump I guess.

### CODE REVIEW

**Comment by volfco** [comment]
Can you increment the version number for this PR?

You beat me to it. I got sidetracked by the protests in Seattle. I'll review this later today

**Comment by nedsociety** [comment]
> Can you increment the version number for this PR?

Eh, I'm not so sure if release management should be handled within a single feature PR :confused:

Wish you stay safe.

**Comment by volfco** [comment]
Fair enough. I'll test tonight 0.1.7 <---> 0.1.7 and then 0.1.7 <---> 0.1.4 and merge this up

**Comment by volfco** [comment]
@nedsociety I've verified your fix works with v0.1.4. 

@choleraehyq Can you push v0.1.7?

**Comment by choleraehyq** [comment]
@volfco Done :-)

**Comment by nedsociety** [comment]
Great, thanks :D

**Pull request merged**
